version: '3'

services:
  cassandra:
    image: docker.pkg.github.com/aperture-sh/cassandra-lucene-docker/cassandra-lucene:latest
    volumes:
    - cassandra_data:/var/lib/cassandra

  tank:
    image: docker.pkg.github.com/aperture-sh/tank/tank:latest
    environment:
      - TANK_DB_HOSTS=cassandra
      - TANK_EXHAUSTER_ENABLED=true
      - TANK_EXHAUSTER_HOST=exhauster
      - LOG_PATH=/app/logs
    volumes:
      - tank_log:/app/logs
    ports:
      - '8888:8888'

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  exhauster:
    image: docker.pkg.github.com/aperture-sh/exhauster/exhauster:latest
    environment:
      - EXHAUSTER_MONGO_HOST=mongo
    ports:
      - 8080:8080

  navigator:
    image: docker.pkg.github.com/aperture-sh/navigator/navigator:latest
    ports:
      - 8081:80

volumes:
  cassandra_data:
  tank_log:
  mongo_data: